### ISSUE TITLE
flickr always only get 200 iamges

### ISSUE THREAD

**Issue by DengpanFu** [amineHorseman/images-web-crawler#2]
Thanks for your job, I had used your script to crawl images from Flickr and found that it can only get 200 images even i set the images' num to 4000. then i found that in your code web_crawler.py line 152, you didn't use the argument _**page**_, while in the FlickrApi's documentation, it says "_**page (Optional): The page of results to return. If this argument is omitted, it defaults to 1**_", so it always return page 1's content. Then I made the follow modification, and it works for me to get 4000 images:
```
for i in range(1, pages_nbr):
            response = flickr.photos_search(api_key=api_key,
                                            text=keyword,
                                            per_page=items_per_page,
                                            media='photos',
                                            page=i + 1,
                                            sort='relevance')
           ......
```
Thanks for your job again, it makes it easier for me to crawl Flickr images

**Comment by amineHorseman** [comment]
Thank you @DengpanFu 
Why don't you add it as a pull request?
